name: flutter_pos_warehouse_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  dartz: ^0.10.1
  fl_chart: ^0.69.2
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.9
  flutter_typeahead: ^5.2.0
  freezed_annotation: ^2.4.4
  google_fonts: ^6.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  loading_indicator: ^3.1.1
  mat_month_picker_dialog: ^1.1.2
  shared_preferences: ^2.3.2
  syncfusion_flutter_barcodes: ^28.1.33

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/menu/
    - assets/icons/
    - assets/icons/alert/
    - assets/icons/nav/

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
